//
// Generated by Copilot on 9/8/2026.
//

#include <stdio.h>

int main() {
    int secret = 7;   // Fixed secret number
    int guess;
    int i;

    printf("Guess the secret number (1-10).\n");
    printf("You have 3 guesses.\n");

    for (i = 1; i <= 3; i++) {
        printf("Guess %d: ", i);
        scanf("%d", &guess);

        if (guess == secret) {
            printf("You win! You guessed the secret number.\n");
            return 0;   // Stop immediately
        }
        else if (guess < secret) {
            printf("Too low.\n");
        }
        else {
            printf("Too high.\n");
        }
    }

    printf("You lose! The secret number was %d.\n", secret);

    return 0;
}